# Generated by Django 4.1.6 on 2024-08-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('text', models.TextField(null=True)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
